### ISSUE TITLE
[PL][Wotlk - instance][Quest] Whatever it takes! - Halls of Lightning

### ISSUE THREAD

**Issue by mrkariox** [Atlantiss/BugTracker#1060]
http://www.wowhead.com/quest=29861

Quest nie dziala,

Loken (http://www.wowhead.com/npc=28923) nie dropi q itemu (http://www.wowhead.com/item=43151).

**Sprawdzane w wersji NORMAL**

**Comment by monibu** [comment]
tested twice on normal and Loken didn't drop his tongue

**Comment by Bildo** [comment]
fixed

**Comment by monibu** [comment]
still doesn't look like it's fixed - tested on norm and hero

**Comment by Bildo** [comment]
Damn the fuck is with this shit...

**Comment by Bildo** [comment]
fixed
