### ISSUE TITLE
[EN][Dungeon-Cata] Halls of Origination

### ISSUE THREAD

**Issue by Varchord** [Atlantiss/BugTracker#1153]
http://www.wowhead.com/zone=4945/halls-of-origination

# [Temple Guardian Anhuur](http://www.wowhead.com/npc=39425)
* Some players can't use levers. When they click them there is character animation of casting but no castbar and nothing happens.

# [Rajh](http://www.wowhead.com/npc=39378)
* Very low melee attack damage. Around 6-7k per hit
* His script is a mess. Sometimes he is just standing there auto attacking tank. Sometimes he is using his [Blessing of The Sun](http://www.wowhead.com/spell=76355) after pull, sometimes not at all
* [Summon Sun Orb](http://www.wowhead.com/spell=80352) should be interruptable. It does no damage or knocback whatsoever 
* [Solar Fire](http://www.wowhead.com/spell=89131) not appearing because of [Solar Winds](http://www.wowhead.com/spell=74108) are not spawning
* [Sun Strike](http://www.wowhead.com/spell=73872) he is not using this ability
* [Inferno Leap](http://www.wowhead.com/spell=87653) gives movement speed bonus but he doesn't leap

# [Isiset](http://www.wowhead.com/npc=39587)
* Very low melee attack damage. Around 6-7k per hit
* [Supernova](http://www.wowhead.com/spell=74136) should't be interruptable. If you turn away you still get disoriented
* [Veil of Sky](http://www.wowhead.com/spell=74133) she's not using this ability
* [Mirror Images](http://www.wowhead.com/spell=109126) They are hitting for 1-2 damage. And i think killing them doesn't block Isiset abilities

**Comment by drlinux92** [comment]
In addition, Rajh seems not having the Sun Energy resource system at all (the secondary bar under his health bar - similiar colour to hunter's focus)!
Youtube link: https://www.youtube.com/watch?v=RoH0RgI83OE
Wowpedia: http://wow.gamepedia.com/Rajh

**Comment by KlawiszQ** [comment]
Snakes on [Temple Guardian Anhuur](http://www.wowhead.com/npc=39425/temple-guardian-anhuur) should spawn like normal mobs, but at at slighty faster rate rather than spawning only when boss pop up the barrier.
In addition the [Earthrager Ptah](http://www.wowhead.com/npc=39428/earthrager-ptah) does not get back after he disappears.

**Comment by Aival94** [comment]
[Earthrager Ptah](http://www.wowhead.com/npc=39428/earthrager-ptah) when cast Tumultuous Earthstorm crash anyone client in melee range.

**Comment by Varchord** [comment]
Update 18.03.2015 rev 4360
Added Earthrager Ptah

**Comment by sunshineinabox** [comment]
Sun orb is not interruptible yet he still does his abilities when you don't interrupt. I think some of the other abilities were corrected.

**Comment by skulldrinker** [comment]
Earthrager Ptah disappears after Tumultuous Earthstorm and does not appear again.

**Comment by IK0Nv2** [comment]
Levers still dont work on HC. On normal seems to work fine (personal observations).

**Comment by 1Andas** [comment]
Earthrager Ptah is yet again disappearing after Tumultuous Earthstorm and does not appear again (I encountered this on normal difficulty, I don't know about heroic).
![wowscrnshot_040316_231240](https://cloud.githubusercontent.com/assets/10603375/14236908/ceaa78a6-fa1c-11e5-9d02-2fab711791aa.jpg)

**Comment by mati865** [comment]
> Some players can't use levers. When they click them there is character animation of casting but no castbar and nothing happens.

Everyone except Dead Knights can use them.
