### ISSUE TITLE
[EN][Quest-Legendary] The Sacret and the Corrupt

### ISSUE THREAD

**Issue by captjvmoore** [Atlantiss/BugTracker#1329]
First congratulations and thank you for scripting ICC 25!

As for the quest The Sacred and the Corrupt http://www.wowhead.com/quest=24545 it is said that you must be friendly with the Ashen Verdict http://www.wowhead.com/faction=1156 in order to pick it up. Right now, the quest can be picked up even in a neutral status with the faction.

Furthermore into the quest chain, once picked up, one of the items required for the completion of the quest is Light's Vengeance http://www.wowhead.com/item=49869 which is obtained in a cave located in Dragonblight. Inside the cave, there should be a cut scene with the Lich King. Here is a video: https://www.youtube.com/watch?v=F-v5Cp8v8Ms

Unfortunately, right now a friend of mine reports that the cave is completely empty, even when you obtain the quest.

I will update on future bugs or any other bugs related to that specific quest in a followup.

**Comment by Blasiren** [comment]
You can obtain the quest (or could, can't test it right now) with any other class that isn't  dk, warrior or paladin. Also I could pick up the quest when i was neutral with ashen verdict, the event in the cave is the biggest "wall" to defeat since we can't pick up the hammer

**Comment by captjvmoore** [comment]
My guild and I ran Icecrown Citadel last night. The place is still very buggy, like for instance Sister Svala http://www.wowhead.com/npc=37126 won't drop here immunity shield and will start randomly impaling players to their death with no animation.

Professor Putricide's http://www.wowhead.com/npc=36678 oozes are very buggy, they are moving faster than usual. Also, on 25 player mode, they should have around 1,95 million health, not 3,5 million, which makes killing they rather impossible. Also, upon wiping, the boss graphics get fixed with his 2nd phase and 3d phase looks, but fix themselves upon engaging the boss.

Gunship Battle encounter doesn't appear to be working.

Festergut http://www.wowhead.com/npc=36626 spore mechanics don't appear to be there, because of which he just enrages with more damage and can 1 shot the raid if the spore mechanics aren't there.

Blood Queen lana'Thel http://www.wowhead.com/npc=37955 biting mechanics aren't there, which makes the encounter a losing dps race, even for people geared with the maximum current Cataclysm expansion gear. Also, her Pact of the Darkfallen spell, which is supposed to be neutralized upon the 3 linked targets coming together is barely visible so people have no way of seeing which targets are linked. Also, the targets have to literally sit on top of each-other, in order to cancel the effect, which is wrong. They are only supposed to come close to each-other.

The Blood Prince council http://www.wowhead.com/npc=37970 for some reason auto dies after a minute or two in the encounter (we just witnessed this last night and even got the achievements associated with the boss.

This is as far as we got, due to Professor Putricide and Sister Svala bugs rendering us unable to continue, and there were more bugs that I can't quite remember. Also the mechanics for the legendary Shadowmourne http://www.wowhead.com/item=49623 need to be implemented correctly with the boss encounters. We were having Rotface and Festergut's Acidic Blood possession issues last night, where one of the players couldn't loot his quest item, which by the way, should have a 100% drop chance.

The entire instance is yet to be tested. I will write a follow up report on this, once we run ICC more times.

**Comment by Bildo** [comment]
test again after update some issues should disapear

**Comment by Blasiren** [comment]
Managed to find id of npcs that should show up (except for the lich king) during the cave "Event" (Wretched ghouls http://www.wowhead.com/npc=37881#abilities) and Vegard the Unforgiven (http://www.wowhead.com/npc=37976/vegard-the-unforgiven#comments) hope that helps

**Comment by Navedonar** [comment]
https://github.com/TrinityCore/TrinityCore/commit/fb1b7f66a5d959e4b080a8b25cd697c9764a098f
https://github.com/TrinityCore/TrinityCore/commit/97d415d1b2a429557f667f9c30e8577ab89e6434

**Comment by captjvmoore** [comment]
Yes Bilbo, I am aware that Wowhead displays information for the official Blizz current WoD expansion. I get my information from official Paragon world first kills, like this one: https://www.youtube.com/watch?v=jv93ko3WeK8

**Comment by captjvmoore** [comment]
Ran ICC 25 last night. The bridge after Lady Deathwisper is escalating OK. But the rest of the issues don't appear to be fixed. I even have more to report:

Rotface's Acidic Blood http://www.wowhead.com/item=50231/rotfaces-acidic-blood and Festergut's Acidic Blood http://www.wowhead.com/item=50226/festerguts-acidic-blood, which are part of the The Sacred and the Corrupt quest http://www.wowhead.com/quest=24545 should only be obtainable by those players who have the quest, with no contest whatsoever. Instead, when we ran ICC last night, since there was Free For All loot enabled, both of these quest items dropped just as any other item would drop, and players just ninja-ed them, simply by clicking NEED, even though they don't have the quest and can't use them.

The quest giver of The Sacred and the Corrupt is a bit buggy and sometimes doesn't respond to interaction.

The rest of the bugs that I have reported in my previous comments here in this thread are still there.

**Comment by Blasiren** [comment]
Thanks for posting these link Navedonar!

**Comment by Nc94** [comment]
It would be nice if someone will made Light's Vengeance ( http://www.wowhead.com/item=49869/lights-vengeance ) an container that drops quest item ( http://www.wowhead.com/object=201937/lights-vengeance ) cuz right now it's blocking the whole chain to make shadowmourne.
The hammer already lies there but is not interactable: http://i.imgur.com/EphrjSS.jpg

**Comment by Blasiren** [comment]
Bump.

**Comment by Bildo** [comment]
i ahve this quest fixed on my local server i jsut need to push to main

**Comment by Bildo** [comment]
fixed

**Comment by Alastia** [comment]
I tried to do this quest yesterday right after the fix, I entered in the Frostmourne cavern and the lich king spawned but he was doing nothing and after 5 min +/- he disappeared, I tried to relog, enter again in the cavern and even take again the quest,but nothing happened. Still bugged for me

**Comment by Nc94** [comment]
Still bugged tried on 2 chars and still there wasn't hammer to start event -> https://www.youtube.com/watch?v=F-v5Cp8v8Ms there was only one lying on floor but I couldn't even interact with it.

**Comment by Bildo** [comment]
yea i know why should be fixed today or tomorrow

**Comment by captjvmoore** [comment]
Unfortunately, this quest still isn't fixed, nor is the Icecrown raid instance. I've tried to obtain the Light's Hammer from the cave. It won't even trigger an event. Even if we manage to get passed this first quest, the infusion chain quests that follow, I have a feeling, won't work as well. We understand you guys are busy as hell perfecting the Firelands, which is a wonderful job. Really hope you pay a visit to the old raids, once you are done with that.

**Comment by Bildo** [comment]
Yes i know this is not fixed, i have fixed this on my local server i jsut need to push it into the main.

**Comment by raduriel** [comment]
This quest is still buged

**Comment by Alastia** [comment]
I'm still waiting for the fix :(

**Comment by Bildo** [comment]
after update

**Comment by Cellhawk** [comment]
Entered the cave tonight, no event, just undead vrykul constantly spawning ghouls. Got to the Light's Hammer, tried to loot it, object contains no loot.

**Comment by raduriel** [comment]
@Bildo 
Entered the cave today , it was insane; Vegard the unforigven(http://www.wowhead.com/npc=37976/vegard-the-unforgiven) was spamming Ghouls (http://www.wowhead.com/npc=37881/wretched-ghoul) and the event goess on and on there + Light's Vengance is still interactable ...
Thanks for you're time and I hope you check it out =)

**Comment by roesiran** [comment]
Still bugged, Light's Vengeance is NOT  interactable and constant spam of ghouls.

**Comment by dr-j** [comment]
I scripted this on tc a few years back I have made changes to script since and my latest implementation https://youtu.be/2VnxP-Eigm4 think someone posted links to my original version of this which was from retail sniff data
