### ISSUE TITLE
[ENG][Talent][Paladyn] Tower of Radiance

### ISSUE THREAD

**Issue by Kejmil** [Atlantiss/BugTracker#1330]
http://cata.openwow.com/spell=85512

This talent always give holy power from Flash of Light or Divine Light, regardless of having or not Beacon of Light.

**Comment by Wolffenstein** [comment]
Fixed in rev 4215.

**Comment by f4llenftw** [comment]
just tested with 1/3 of the talents and still gets you holy power when you flash heal yourself

**Comment by Piklo** [comment]
@f4llenftw open new issue
