### ISSUE TITLE
[PL][Profession][Quest][Jewelcrafting] Figurine - [...] Trinkets

### ISSUE THREAD

**Issue by Qwers** [Atlantiss/BugTracker#1355]
Figurine - Jeweled Serpent  http://www.wowhead.com/item=65896
Start: Broken Serpent Figurine  http://www.wowhead.com/quest=28775
Reward: Figurine - Jeweled Serpent  http://www.wowhead.com/item=52353

Figurine - King of Boars  http://www.wowhead.com/item=65895
Start: Broken Boar Figurine  http://www.wowhead.com/quest=28778
Reward: Figurine - King of Boars  http://www.wowhead.com/item=52351

Figurine - Earthen Guardian  http://www.wowhead.com/item=65897
Start: Broken Earthen Figurine  http://www.wowhead.com/quest=28776
Reward: Figurine - Earthen Guardian  http://www.wowhead.com/item=52352

Figurine - Dream Owl  http://www.wowhead.com/item=65894
Start: Broken Owl Figurine  http://www.wowhead.com/quest=28777
Reward: Figurine - Dream Owl  http://www.wowhead.com/item=52354

Figurine - Demon Panther  http://www.wowhead.com/item=52197
Start: Broken Panther Figurine  http://www.wowhead.com/quest=25047
Reward: Figurine - Demon Panther  http://www.wowhead.com/item=52199

Żaden z powyższych questów nie działa, co uniemożliwia zdobycie któregokolwiek z w/w trinketów. Pomimo posiadania wymaganych matsów questa nie można ukończyć. Pokazuje sie okienko, ale nie można kliknąć "continue", a tym samym również "complete".

**Comment by Wolffenstein** [comment]
Fixed in rev 4268.

**Comment by Canoodle** [comment]
Broken Owl Figurine is still not working.
Figurine - Dream Owl http://www.wowhead.com/item=65894
Start: Broken Owl Figurine http://www.wowhead.com/quest=28777
Reward: Figurine - Dream Owl http://www.wowhead.com/item=52354

Can confirm that Broken Serpent Figurine works.

**Comment by TheCopacabanaMan** [comment]
Broken Panther Figurine dont work.
I have all materials, when i hit the "Continue" button, nothing happen. 
It should complete quest.

Please, may you check? Thanxie :)
