### ISSUE TITLE
[EN][Quest][Darkshore] Soothing the Elements

### ISSUE THREAD

**Issue by Nosere** [Atlantiss/BugTracker#1521]
http://www.wowhead.com/quest=13580/soothing-the-elements

What happens:
The first wave of mobs spawn in (one or two http://www.wowhead.com/npc=34368/fire-elemental-remnant), 
after that wave no other mobs spawn in. After a while the totem (http://www.wowhead.com/item=46546/energized-soothing-totem) just despawns and the quest is not completed.

What is supposed to happen:
http://youtu.be/RZa6hZapjMw?t=2m

**Comment by ammeba** [comment]
Up, not working. What about autocomplete, until you fix it? :>

**Comment by deplecak** [comment]
agree about autocomplete, i met lots of people today that tried to finish this quest as well.

**Comment by fizzle7** [comment]
Indeed, autocomplete would be best for now.

**Comment by darklord88** [comment]
did it after 50 tryed xD

**Comment by ammeba** [comment]
did you took the quest 50 times or just spawned the totem 50 times? :D

**Comment by deplecak** [comment]
just tried after someone told me how to complete it, you spawn totem and stand back in place where fire elements are spawning and keep keeling them....completed this quest minute ago.

**Comment by Andarien** [comment]
But they are NOT spawning! How did you complete it? Nothing happens!

**Comment by ammeba** [comment]
Aaaand it's me again! I was trying about 10 minutes and I did it... I keep clicking the totem untill it finally worked. After that a few mobs spawned and final "boss"... So, I can say it is working but you must be very patient :P

**Comment by deplecak** [comment]
@Andarien yes i completed it on atlantiss, and yesterday i witnessed another player finishing this quest as well.

**Comment by Andarien** [comment]
Doesn't work for me, tried many times for like 30 minutes... Maximum two elementals spawn and then nothing

**Comment by agusgk13** [comment]
Yes, the same happened to me, most of the time was one elemental. But sometimes there were two.

**Comment by deplecak** [comment]
hit me up in game (char name: deplecak) and i will help you with this quest

**Comment by Ash1993** [comment]
I've just completed it this morning as deplecak said a few comments before. After I spawned the totem I went quickly to the exact place where the elementals appear. I think the trick is killing them as fast as possible. So it seems to be doable

**Comment by Griskhet** [comment]
I tried more than 30 times, it doesn't work, always spawn one mob, i kill him as soon  as he appears and then nothing happens.

**Comment by Maxad2234** [comment]
i've been trying to complete this quest for 3 days, for nothing. even managed to kill fire elemental rager... 3 times. quest still can't be completed. and i think the trick about spawning them is a little different: they can't get past certain point. i think it's somewhere between burning tree and first pillar from that fiery altar.

**Comment by Wolffenstein** [comment]
Fixed in rev 4420.

**Comment by bemoi** [comment]
Hi,
this issue is not fixed yet, people who were commenting were talking about not being able to defeat the elementals or not being able to locate the place to place the totem, while our issue is different, that no elementals appear when totem is placed in the right place.
