### ISSUE TITLE
[EN] [QUEST] [Tirisfal Glades] Recruitment 

### ISSUE THREAD

**Issue by Angelo-DM-** [Atlantiss/BugTracker#1592]
This quest should be horde side, instead it has "undead restriction".

http://www.wowhead.com/quest=26800

This quest unlock two more quests (in order):

http://www.wowhead.com/quest=28653 (that only undead and Blood Elf could do it)

and

http://www.wowhead.com/quest=26801

As Blood Elf, i can't take this quest.

**Comment by Bildo** [comment]
fixed in rev. 4274

**Comment by Angelo-DM-** [comment]
I still not be able to pick up this quest...

I've tried to delete cache folder and relog... but it does not work...
