### ISSUE TITLE
[EN][NPC][Howling Fjord] Falcon Versus Hawk

### ISSUE THREAD

**Issue by Norfik** [Atlantiss/BugTracker#1670]
http://www.wowhead.com/quest=11468/falcon-versus-hawk

Using item "Trained Rock Falcon" (http://www.wowhead.com/item=34121/trained-rock-falcon) on Fjord Hawk (http://www.wowhead.com/npc=24747/fjord-hawk) don't give credit.

**Comment by Bildo** [comment]
fixed in rev. 4274

**Comment by ariean** [comment]
Still doesn't seem to work. It keeps saying 'Invalid Target'.

**Comment by Bildo** [comment]
strange because for me it works, maybe clear cache ?

**Comment by xandis1** [comment]
You have to quit and retake the quest. Also, you need to be very close to the hawk you are targeting...

**Comment by jissabraham** [comment]
oo it works if ur close to hawk
