### ISSUE TITLE
[EN][Quest][Darkshore] Cleansing the Afflicted

### ISSUE THREAD

**Issue by fizzle7** [Atlantiss/BugTracker#1746]
Quest http://www.wowhead.com/quest=13545/cleansing-the-afflicted is bugged because the mobs http://www.wowhead.com/npc=33043/maddened-blackwood you are supposed to cleanse keep attacking you after you kill the slime(http://www.wowhead.com/npc=33000/spirit-of-corruption) in the following way:
1. If you are in melee range of the furbolgs, after casting the Herb they attack you in melee and after you kill the slime they turn green and say their line, but still keep attacking you in melee.
2. If you are away and cast the herb, the furbolg casts Wrath at you and if you then kill the slime, the furbolg runs towards you, while turning friendly and saying the line, and attacks you in melee.
As Night Elf, if you shadowmeld then they stop attacking you and if you then move, they stay at the same place you were shadowmelded.

Obviously they should stop attacking you and disappear after some time, proof: https://www.youtube.com/watch?v=xbCmP8M-N4M

Edit: Actually they sometimes disappear, but not always, however they keep attacking you before disappearing.

**Comment by lcorr031** [comment]
It is 9/15/15 and this bug is still not fixed. All of the issues state above have not been fixed!

**Comment by TranceAccount** [comment]
Confirmed

**Comment by Bildo** [comment]
fixed

**Comment by BorniPL** [comment]
Not fixed for me it seems. Used Herb on Corrupted Blackwood, killed the slime, Blackwood turned friendly and still attacked me - couldn't lose him even using Shadowmeld.
