### ISSUE TITLE
[EN][Achievement][Low priority] Onyx Panther

### ISSUE THREAD

**Issue by monibu** [Atlantiss/BugTracker#1986]
http://www.wowhead.com/achievement=3896/onyx-panther

Obtaining http://www.wowhead.com/item=48527/enchanted-onyx and learning http://www.wowhead.com/spell=67527/onyx-panther doesn't reward us with feats of strenght achievement mentioned above.

**Comment by monibu** [comment]
Fixed rev. 4464, thx to Andysc

**Comment by monibu** [comment]
Sorry, confused Onyx Panther with Onyx Idol.
Andysc fixed Onyx Idol (token from AQ10), but the Onyx Panther achi is still bugged.

**Comment by Bildo** [comment]
fixed

**Comment by monibu** [comment]
I wouldn't say it's fixed - ppl who got the pet before fix was implemented still don't have the achievement

**Comment by Dziara** [comment]
Well it isn't fixed for new owners as well. Confirmed today :(

**Comment by Aviannaqt** [comment]
Still Bugged - 04.12.2017
