### ISSUE TITLE
[EN][Quest] Secrets of the Tower

### ISSUE THREAD

**Issue by masterskull** [Atlantiss/BugTracker#2338]
I've tried finishing the quest, but it's not working at all.
Wowhead link: http://www.wowhead.com/quest=26290/secrets-of-the-tower

Edit: Quest does get completed after a couple minutes but still not working as it should.

**Comment by Swepy** [comment]
can you tell me how did you finish it? im waiting where the npc's suppose to be, but i cant complete the quest. did you use that quest item? where did you wait?

**Comment by Dexobox** [comment]
:+1: +1 

I cant complete this quest, i guess the workaround here is broken as well now, i am unable to use the quest object [Potion of Shrouding](http://www.wowhead.com/item=58112/potion-of-shrouding) to change phase it only gives me a invisibility buff.

I spent like 30 mins on 2 different days to see if being present in top level of the tower where the scenario plays out would mark the quest complete but nothing happens.

**Comment by Thefakemccoy** [comment]
This quest is can be completed. 
![wowscrnshot_053015_192001](https://cloud.githubusercontent.com/assets/12252441/7899803/ed493a96-0700-11e5-998c-57673ccec287.jpg)

There is a problem with the quest. You have to target yourself with the flask for one. Which it should be self cast on you once you click the veil inside the door.

If you try to click it while one of the elites is targeted it casts it on them.
![wowscrnshot_053015_192158](https://cloud.githubusercontent.com/assets/12252441/7899812/25d4e7fc-0701-11e5-9a23-d626a28947da.jpg)

**Comment by SuperPacman** [comment]
I try for many hours to finish this q but it is not possible, It happens just like Thefakemccoy wrote

**Comment by matthewcl375** [comment]
This still doesn't work, the potion buff is applied but the NPCs fail to materialize and the dialogue doesn't happen. This effectively breaks the Westfall quest chain making it impossible to achieve the final quest rewards for the zone from King Varian Wrynn.

This worked fine when I last tried it a few weeks ago.

**Comment by mikonek07** [comment]
Still bugged, at first potion which shouldnt be possible to use at anybody exept the owner, second about quest - waiting at the top of the tower doesnt provide to any action - quest cant be completed. If there is a possibility, it's still bugged and too random.

**Comment by Mayakii** [comment]
Just did it as soon as I got there. Sneak through the hostile NPCs and make sure you don't have any aggro on you. Get to the very top of the tower, use the potion and then right click the buff to remove it. After doing so, the dialogue should happen, if not, try using the potion again and removing the buff again.

**Comment by Peglaa** [comment]
Day 359.. quest still not fixed.. it's kinda frustrating.. phasing when using the potion seems to work.. but on the top of the tower nothing happens.. the quest cant be completed.. tried many times and many options.. nothing works.. any news on fixing this ? Prolly needs to be rewritten from scratch.

**Comment by Mayakii** [comment]
@Peglaa it works. Give my comment a look and try that.

**Comment by Peglaa** [comment]
@Mayakii as I said.. I tried everything.. it just didn't work, there was a few ppl doing the quest also and it didn't work for them either.. this thing needs to be rewritten all over.

**Comment by Mayakii** [comment]
@Peglaa Ugh, weird. I helped one guy with this quest that came couple mins after me, and it worked for him o .o oh well, either way, it should be fixed nontheless.

**Comment by Peglaa** [comment]
@Mayakii too bad.. I figured this was fixed by now but I guess they had some other stuff to deal with, would be nice tho.. this is one of a few quests that don't work from 1-60 lv range

**Comment by Lebiedz** [comment]
It's been more than two weeks since the last comment, so I'd like just to remind devs that this quest is still broken and undoable (I've tried every option that I and others in this topic came up with).

**Comment by v0j4** [comment]
I almost gave up on this quest but then i tried using the flask while I was on the stairs and not on the top of the tower, and the guys showed up :)

**Comment by Thefakemccoy** [comment]
Here i made a pic to try to help people more until the trigger point can be adjusted.
![wowscrnshot_121915_094802](https://cloud.githubusercontent.com/assets/12252441/11913576/7299db72-a636-11e5-82c1-251b06f86143.jpg)

**Comment by Emielos** [comment]
I have tried every suggestion in this report, but nothing works.
If anyone has a tip on how to complete this please share it.

**Comment by tristanvm** [comment]
Can confirm that the quest is completeable by standing in the red circle as shown above. However [Potion of Shrouding] does not work (http://www.wowhead.com/item=58112) and Agent Kearnen does not show the elites as she should be doing.

**Comment by Chasstastic** [comment]
Tried everything here and it wont work. Any tips?

**Comment by Chasstastic** [comment]
Now there's mercenaries INSIDE the tower when the potion is active. WHY IS THIS SERVER TURNED SO BUGGY FFS

**Comment by reapertg** [comment]
This is still an issue. Oddly I did this quest earlier today with another toon, and the quest auto completed a few seconds and picking it up. Yet when i come to do it on this toon...no such luck. As others have said I have tried waiting in the tower, waiting by the questgiver, standing in the spot on the stairs, toggling the buff on and off countless times....whatever is supposed to trigger the event at the top of the tower is not registering :( Uncompletable and breaks the zone's main quest chain.

**Comment by Peglaa** [comment]
As I said.. this needs to be completely rewritten from scratch.. too many weird stuff affecting it.. it's a complete mess. Wolf did rewrite elwynn forest recently. maybe westfall is next.. cause it sure as hell could use one :)

**Comment by Ntfk** [comment]
Please fix this quest.

**Comment by ManiaqGH** [comment]
Still bugged and none of the "fixes" above help.

**Comment by madethatway** [comment]
Still bugged. Unable to complete. Can't take potion at all - get error message "invalid target" or no error message at all.

The strange thing is that I was able to complete this on a shaman alt earlier in the day - although I died as soon as the Helix dialogue began (no idea why, I wasn't being attacked), I remained a corpose until it was finished, then rezzed.

But on my mage no such luck.

This quest has been a pain for a long time.

**Comment by Illusionist87** [comment]
This quest is still bugged, and it looks like it is going to stay that way.

**Comment by Khangu** [comment]
Confirmed. Quest used to work few months ago but now there is no way to activate conversation. Using and canceling potion on self in different parts of the tower (including the magic stairs spot) does not trigger anything. Canceling and retaking quest doesn't help either.

It's sad that new fixes often make repaired ealier things bugged again and they stay in that condition.

**Comment by Avalain** [comment]
Still not working. 

I can confirm it was working previously but now nothing helps and more and more people come to tower just to get irritated.
Used elixir at tower's entrance, near stairs, waited for debuff to wear off itself and so on.
It's just bugged.

**Comment by Xenerus** [comment]
Still nothing. Once per restart you say? Is there a restart once per day at least?

**Comment by w273** [comment]
Quest is still bugged but I managed t complete it somehow. I tried the things suggested here and none of them worked. Server disconnected, then I picked up the quest again and started approaching the tower from the right side and it auto-completed before I even set foot into it.

**Comment by Xenerus** [comment]
Yes, completed it as well. Works after restart. That's not enough, though.

**Comment by Lebiedz** [comment]
I did this quest yesterday on 2 characters one after another and I think I've found a workaround.

What I've done was to drink the potion while running up the tower, somewhere at the bottom of it. Then I walked to the place that @Thefakemccoy showed on the screenshot in his post and right-clicked on the invisibility buff from potion. This triggered the event.

This "tactic" worked on 2 of my characters, without any problem. And on one of them I wasn't able to do this quest earlier.

**Comment by user1011** [comment]
Bump.

**Comment by Khangu** [comment]
It's one of many quests that works only after reset/crash/down/etc. If you really want to complete it log out near end of stairs and check from time to time or do it right after server is UP.

**Comment by arndry** [comment]
I tried the sugestions but doesn't worl for me....

**Comment by deathmace** [comment]
Still broken... please make autocomplete or a way to complete it at least

**Comment by Ahanai** [comment]
Tried to complete it yesterday by using the following tips, still uncompleteable to me. Without the quest players can't achieve Loremaster, please repair it somehow

**Comment by Dahours** [comment]
Yesterday was work .I did it.Thanks and i hope will work for Everyone.

**Comment by arndry** [comment]
let me check if i can do it.... what u did to make it work?

**Comment by Varriesa** [comment]
Still broken, but it can be complete after the restart.

**Comment by Snake90** [comment]
Still bugged ... if you can't fix it,  just autocomplete the quest :/

**Comment by Bildo** [comment]
quest rewritten

**Comment by Griskhet** [comment]
Still doesn't work, i waited 30 minutes and tried everty tip suggested in this topic, it just doesn't work.

**Comment by ia2115** [comment]
Just came to this quest today, nothing works not even after server crash. please fix or auto complete thanks in advance.

**Comment by Bildo** [comment]
You have to use spell item. Event will start only if you have aura on yourself.

**Comment by ia2115** [comment]
it was tried with a GM watching, and no it didnt work but the kind staff member completed it for me and i got on my way.. Thanks for helping it was nice to see it, but for others i hope they get it fixed as it seems to affect a lot of ppl. I guess when you say aura you meen the potion of invisibility provided by the quest giver.

**Comment by Noviush** [comment]
I've tryed all ways tiped above (except GM's assistance :P), still not working for my 2 alts...

**Comment by victordavid23** [comment]
25/9/16, still nothing, its bugged, please help.

**Comment by WilsonStark** [comment]
Yes. it's still bugged potion works even mobs appears but after that nothing happens.

**Comment by swiftdeath** [comment]
Any intel on this? It's still bugged

**Comment by pelekon** [comment]
> Any intel on this? It's still bugged

Nah only amd :/

**Comment by ZFake** [comment]
> Yes. it's still bugged potion works even mobs appears but after that nothing happens.
I second this. The models appear if the potion is imbided, however, nothing happens to advance the quest. Also, the potion's visuals are not applied.

**Comment by krecik88** [comment]
fixed in 5244

**Comment by needybastard** [comment]
No, no it is not fixed in 5244. Open it back up.

**Comment by krecik88** [comment]
script itself is ok, but we will have to put diffrent core branch on main server to get it working properly.

**Comment by Khangu** [comment]
So the only way to complete it is still be first after res?

**Comment by Awkakelen** [comment]
Still doesn't work. Nothing happens when i came upstairs. That girl is talking with no goblin, but with a big guy.

**Comment by Annowme** [comment]
This was bugged for me tonight. I entered the tower and used the potion, then I got the invisible buff, however there was no visual effect despite the buff. I went to the top of the tower and saw the shadowed figures, but there was no dialogue. I right clicked on the buff and the figures vanished. I clicked on the potion again and they reappeared, but still no dialogue. Another player was standing near me (not in a party) and stated locally that they, too, got the same results.

**Comment by Khangu** [comment]
There should be goblin at the top of bigger (hobgoblin) shadow figure. I catched him shortly after res and from what I saw another player that came few moments after me also got his Q completed.

**Comment by Annowme** [comment]
@Khangu there is only the Hobgoblin and Human female figures at the top of the tower, both shadowy. No Goblin. Neither of them say anything or can be targeted/interacted with. I just tried again about forty-five minutes ago, running through all of the "tricks" of this thread. Nothing. No dice. I opened a ticket and added a bug report in-game, but then had to log off before hearing anything.

**Comment by Khangu** [comment]
For this quest and bunch of other there is only one solution. Log out there. Wait for reset/down/crash and when server stands up login and do it. Really there is no point in waiting with open ticket or running around and spamming potion.

What I wonder... There is very similiar quest at Azuremyst Isle but instead of drinking potion we use tree disguise kit (http://www.wowhead.com/quest=9531/trees-company) and this one works perfect all the time. We use item, 2 npc spawns and talk, q completed. I don't know if this can be copied and implemented here... So just sayin'.

**Comment by Annowme** [comment]
I did Trees Company without issue on the same character, as you say. When should I expect a server restart in order to reattempt Secrets of the Tower?

**Comment by krecik88** [comment]
fixed

**Comment by krecik88** [comment]
fixed in 5287

**Comment by Assenat** [comment]
The same issues are still on. Firstly, Agent Kearnen does not shoot to mercanaries. Secondly, the potion does not make this shady effect. And thrid, but most important, after drinking potion and reaching top of the tower, the dialogue isnt triggered.
