### ISSUE TITLE
[EN][Achievement] Trial of the Champion

### ISSUE THREAD

**Issue by LaveniaGithub** [Atlantiss/BugTracker#3388]
Not all the bosses in Trial of the Champion gives credit for killing them.

![trial of the champion achievement](https://cloud.githubusercontent.com/assets/12621497/7840025/c95aa808-0495-11e5-9d0f-4e60e9b68cef.png)

**Comment by aranguard** [comment]
We did it 3 ppl for achieve only 1 of us got credit for Eadric the Pure.It looks like some of them random for players.

**Comment by Bildo** [comment]
fixed

**Comment by amonkira88** [comment]
It isn't fixed,  was there yesterday. It didn't work propellery. I had credits only for Argent Confessor Paletress and The Black Knight. When we swich on heroic mode and did it again I gained credit for Eadric the Pure.
