### ISSUE TITLE
[EN][Spell][Priest] Mind Flay

### ISSUE THREAD

**Issue by Shisai** [Atlantiss/BugTracker#4308]
mind flay (http://cata.openwow.com/spell=15407) is currently bugged, if you clip it with another mind flay between the second and third tick you lose a tick, meaning with 2 casts you get 5 ticks instead of all 6, however when you clip (recast mind flay) before the last tick, the last tick should be added to the next cast, giving it a total of 4 ticks, so both mind flays should have a total of 6 ticks, the same way dots behave (recasting before the last tick adds the last tick onto the next cast)

heres some videos that show what I mean, https://www.youtube.com/watch?v=XUG_g_uftFU and https://www.youtube.com/watch?v=HFKy9RUJ2gA

as you can see when they cast mind flay the first time it has 3 ticks, however they clip it just after the second tick, their second mind flay has 4 ticks as it has added the final tick from clipping the previous mind flay.

**Comment by Illusie** [comment]
Clipping is part of the game, what about another classes checked it out?

**Comment by Jenovas** [comment]
This mechanic already works for dots. Say you are a feral Druid and you refresh your Rip just before the last tick the new Rip will tick one more time than it normally would. This only works if you refresh DoTs before the last tick. As for Mind Flay it is a channel, so we might need to add this mechanic to channeled spells.

**Comment by bonfax4** [comment]
BUMP. Making shadow priests weaker then they already are specially when the tick timer is also reseted every time you recast or attempt to clip.Leads to a considerable dps loss altogether.

**Comment by Kejmil** [comment]
it is fixed with mind sear clipping on zori local server already

**Comment by pignon87** [comment]
well change the label then..btw new bug about mind flay is on now https://github.com/Atlantiss/BugTracker/issues/6301

**Comment by pignon87** [comment]
the bug https://github.com/Atlantiss/BugTracker/issues/6301 is still present

**Comment by anxanas** [comment]
This is a very annoying bug, a way to somewhat counter it is to use the macro:
#showtooltip Mind Flay
/cast [nochanneling:Mind Flay] Mind Flay
so you wont interupt the channeling mind flay when u are still channeling it, that way you can spam the button and not lose precious ticks due to using Mind flay too late or too early

**Comment by pignon87** [comment]
@anxanas That macro should be a dps loss macro with a properly working Mind flay. But yes,with the bug it helps :)

**Comment by kadi2** [comment]
fixed in rev. http://atlantiss.eu/changelog#rev4920
