### ISSUE TITLE
[EN][Quest- WotLK][Howling Fjord] Lightning Infused Relics

### ISSUE THREAD

**Issue by morgs71** [Atlantiss/BugTracker#4335]
Walt at the Explorers' League Outpost in the Howling Fjord wants you to use the Iron Rune Construct's Collect Data ability to collect 15 sets of Iron Rune Data.

Dismiss your construct by dismissing it from the pet window once you have completed the quest.

    Iron Rune Data Collected (15) 
------------------------------------------------------------------------------------------------------------------

Clicking on the table will give you the option to put the suit on, but will not accept a mouse click and activate.  Without the suit of armor you cannot do the quest.

**Comment by kzlatkov** [comment]
Confirmed. Still not allowing to put the suit on. Staying bugged does NOT allow players to proceed further in the whole Howling Fjord zone.

**Comment by morgs71** [comment]
Looks like it was fixed on trinitycore DB could we possibly get it pushed into our DB?

TrinityCore/TrinityCore#14269

**Comment by morgs71** [comment]
still broken need to finish to move on with rest of zone quest line

**Comment by jissabraham** [comment]
still broken suit cant be put

**Comment by Bildo** [comment]
fixed

**Comment by Lycanar** [comment]
No it's not fixed, don't close the thread if it's not properly done. Quest still cannot be completed, the keeper doesn't appear and the scene does not roll out. Bluff does not work either.

How it's supposed to be: https://www.youtube.com/watch?v=O98BhP_zJBU
