### ISSUE TITLE
[EN][Quest][Borean Tundra] Abduction

### ISSUE THREAD

**Issue by iliarakov** [Atlantiss/BugTracker#4651]
hello the npc is green and I cant  captured Sorcerer when they a green I search for more but I don't find I find only green and I cant attack I use the quest item but don't work  see my screenshot see video 
http://www.wowhead.com/quest=11590/abduction#videos
https://www.youtube.com/watch?v=UMLZt759z3U
http://prntscr.com/8pr1q7

**Comment by RandomPickNewb** [comment]
There are plenty that can you capture just look for the "red" ones. And also the following quest tends to be a bit buggy it sometimes works and it sometimes doesnt(this might apply for this quest as well idk)

**Comment by Messerx** [comment]
well I looked nearly everywhere and there where only green ones

**Comment by Thefakemccoy** [comment]
It seems once some one has captured them they turn green and wont respawn like they should
![wowscrnshot_112315_130750](https://cloud.githubusercontent.com/assets/12252441/11345138/40635dc0-91e3-11e5-8f36-b7b2781d7cfe.jpg)

**Comment by iliarakov** [comment]
i know they fix thats long ago

**Comment by cosminush** [comment]
on 08.06.2016 its still bugged, they dont become friendly and follower to the tower, and the quest have a questline.

**Comment by Cellhawk** [comment]
Prerequisite for profitable, well-rewarded and good quest chain, should be fixed as soon as possible

**Comment by krauza666** [comment]
Still doesn't work. 
![2016-09-26 1](https://cloud.githubusercontent.com/assets/13641485/18849368/f50c6522-8432-11e6-8205-0b4cf05a5262.png)

**Comment by reapertg** [comment]
over a year later, this still isn't working. As previous posters have stated, the Beryl Sorcerers are always green and cannot be made to follow back to camp for quest completion.

**Comment by krecik88** [comment]
fixed in 5271
