### ISSUE TITLE
[EN][Core]Click guild bank game crashes...

### ISSUE THREAD

**Issue by l337g0g0** [Atlantiss/BugTracker#4929]
![wow atlantss exe crash clicking guild bank](https://cloud.githubusercontent.com/assets/15808479/11166420/8fbf5a2a-8b00-11e5-984d-fa25328e2e87.jpg)

**Comment by l337g0g0** [comment]
![wow atlantss exe crash clicking guild bank](https://cloud.githubusercontent.com/assets/15808479/11166416/6cfac39e-8b00-11e5-8ee0-e4d302f59564.jpg)

**Comment by Avalain** [comment]
I noticed a gear you can equip, putted inside of bank tabs, could crash your client. I resolved issue by removing those items from it.

**Comment by l337g0g0** [comment]
I'll clear my bank tabs and try to isolate it...
TY...

**Comment by Aival94** [comment]
It might be good to merge this one report with this one: https://github.com/Atlantiss/BugTracker/issues/4805

Btw what item was exactly.Before long i tried to clear all the Guild bank and no item alone seems to cause the bug.

**Comment by l337g0g0** [comment]
Admin you can merge if you like...

**Comment by Avalain** [comment]
In my case it was some crafted cloth gear (blues) I was gathering and plenty of Damaged Necklaces. I had them on second tab and each time I clicked on it, crash. It was possible to remove them nevertheless. After that client crashes stopped. I tried to remove items one by one to determine which caused crashes.

**Comment by aje** [comment]
can you give the full wow error message please

**Comment by Aival94** [comment]
Using my miniclient(not exactly the atlantiss one):
Using addons:
[2015-12-18 17.27.43 Crash.txt](https://github.com/Atlantiss/BugTracker/files/66774/2015-12-18.17.27.43.Crash.txt)

**Comment by aje** [comment]
thanks for the answer. Can you give me the name of your guild please. I want to join to try to reproduce the bug

**Comment by Aival94** [comment]
Tears of Goddess.

**Comment by Aival94** [comment]
Sorry but can i ask why this report got closed together with all of the other GB crash reports?

My guild still continue have such crashes from GB so i suppose is not fixed yet.

If there is an other Report is possible to link it here as i want to track it for news about this bug or if there is not should i make a better/proper one by the rules of Bugtracker?

**Comment by Bildo** [comment]
Well since no one was bumping since december i thought it was fixed

**Comment by Aival94** [comment]
Oh.I understand.It still occurs. @aje took some wow errors from my guild but not sure if he is event help anymore Atlantiss.

**Comment by aje** [comment]
I tried to correct it but I had no idea why it happen and I abandoned trying to fix it. but this is still buged

**Comment by Aival94** [comment]
Bump so this one will not be closed.

**Comment by karhima** [comment]
Having the same issue every time I open the guild bank for the first time on a given day. Then it often works for the day. Really annoying.

**Comment by Aival94** [comment]
Bump.

Seems this bug occurs because of the Gear with Random stats generated on them like Cataclysm Green gears.(this might be a cause of leak or when you open gb the server try to put back again some new random stats on the gear and all this is going to client so it cause the crashes)

**Comment by sokkye** [comment]
Bump.  Been having issues with the game crashing while organizing the Guild Bank.  Sometimes it crashes as soon as I open the interface.

**Comment by Aival94** [comment]
bump.

**Comment by Samineh** [comment]
[Eror.txt](https://github.com/Atlantiss/BugTracker/files/1032759/Eror.txt)
@namreeb

**Comment by namreeb** [comment]
@Samineh this appears to be unrelated to the guild bank.  Your client crashed due to what appears to be heap corruption when unloading the M2 model data from the map you were leaving.  This heap corruption is likely due to a malformed packet from the server received earlier on.  However as these logs contains no data about packet history, it does not have the necessary information to locate it.

**Comment by namreeb** [comment]
@Aival94 

I looked at your `2015-12-18.17.33.21.Crash.txt` error log, and this crash happened during Lua's garbage collection.  From the crash log:

> Total lua memory: 15499KB

That is rather excessive for not having any addons loaded.  Do you have any notion of the size of your guild bank activity log?  One possible explanation would be that the guild bank activity logs sent to your client are so large it ran into some internal limitation on lua heap space.

**Comment by Aival94** [comment]
From this time no but if you want i can get a new crash log and give it to you with more info if you want.

**Comment by namreeb** [comment]
Sure.  Here are some questions to answer:

1. When does the crash happen?  When opening the guild bank?  Switching tabs?  Moving items between the guild bank and your inventory?  Moving items around within the guild bank?  Closing the guild bank?
2. Regardless of what causes it, does it happen every time you perform this action?
3. Prior to opening the guild bank, how much memory is your interface using?
4. After opening the guild bank, how much memory is your interface using?
5. Close the guild bank.  Now how much memory is your interface using?
6. Are other members of your guild affected?

**Comment by Aival94** [comment]
1. It can happen anytime during the opening and after the opening of the Guild bank.
2. No. Sometimes it never cause the crash. Seems kind of random.
3. It use the same as when opening Guild bank as far as i saw it.
4. It use the same as when not have opened Guild bank as far as i saw it.
5. The same.
6. If not all at least 90% is affected.
[2017-05-31 00.28.49 Crash.txt](https://github.com/Atlantiss/BugTracker/files/1039762/2017-05-31.00.28.49.Crash.txt)
[2017-05-31 00.35.31 Crash.txt](https://github.com/Atlantiss/BugTracker/files/1039763/2017-05-31.00.35.31.Crash.txt)

**Comment by xmesaj2** [comment]
rev. 5433 should fix it, let me know if bug persists after update

**Comment by Aival94** [comment]
yeah. I will try to keep you updated :). Ty :)

**Comment by Aival94** [comment]
@xmesaj2 For now seems there is no crash. I suppose you can close it and if need i will comment it or make a new bug report

**Comment by xmesaj2** [comment]
Thanks for feedback
