### ISSUE TITLE
[PL/EN][Priest]Divine Aegis + Atonement bug

### ISSUE THREAD

**Issue by Nouitra** [Atlantiss/BugTracker#5035]
Moge potwierdzic ze problem nie zostal jeszcze rozwiazany. Crity z Smite/Holy Fire nadal nie procuja Divine Aegis. W rev 4331 wprowadzono critical heala z atonementa i co za tym idzie proc Divine Shielda.
Natomiast w rev 4567 odjeto mozliwosc critowania z atonementa i system nie uznaje crita ze smita jako critical heala w nastepstwie nie procuje Divine Aegisa.
Szybka naprawa byla by mile widziana ze wzgledu na duzy inbalance zwiazany z tym bugiem.

This problem have not been solved yet. Crits from Smite and Holy Fire does not proc Divine Aegis. In rev 4331 patch was introduced that was supposed to fix the problem with atonement and divine shield : "Atonement heals can now crit and proc Divine Aegis". Then bug was discovered that healing from atonement was crting twice so:
In rev 4567 fix was introduced that took away ability to crit with atonement. Systems thanks to that AWESOME change now does not trigger Aegis cause the heal from atenement ( even when smite and holy fire crit ) is not considered a crit. 
Just to clarify things ( some1 already wrote in the past how the atonement and divine aegis should work but no1 listened ):
When we crit with Smite, lets say 10k we should get heal of the same amount ( unless we got archangel buff which gives us 3/6/9/12/15% more healing ) but that heal should be considered a crit and should proc Divine Aegis. With Archangel buff and basic mastery=30%, it should go like this:
Smite crit =10k so Heal = 10k+15% from Archangel buff = 11,5k + a bubble = 3450 x 30% = 4485 Divine Aegis.

**Comment by Beatit** [comment]
bump :)

**Comment by Nouitra** [comment]
bump

**Comment by Beatit** [comment]
High Prority for priest!!!
I saw in the changelog a million patches for druid, shaman or mage, and nothing concrete for the Priest, and this is a big bug on a minus for the Priest...

**Comment by Kejmil** [comment]
if smite/holyfire (direct or dot) crits, then atonement heal from smite should be labeled as crit (but healing won't be multiplied by crit heal multiplier) and because of this this crit should proc divine aegis

**Comment by Erthar** [comment]
bump

**Comment by Kaldros** [comment]
Bump as this is a very needed change for Priests. Please fix this.

**Comment by Venomenalny** [comment]
I would bump too with this. I want my atonment build back.

**Comment by linesar** [comment]
ohh god, so looking forward to this fix.

**Comment by Kaldros** [comment]
Bump. Please look into this.

**Comment by stanq87** [comment]
bump

**Comment by Jenovas** [comment]
Should be fixed in rev. 5002

**Comment by struggle86** [comment]
Smite and the Holy Fire dot crits are applying Divine Aegis, but the initial burst damage crits from Holy Fire are not. Still broken.
