### ISSUE TITLE
[EN][Quest][Shadowmoon Valley]Teron Gorefiend, I am...(ID 10645)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5376]
Quest is not working at all as event is not starting.You are not transformed or the NPC [Karsius the Ancient Watcher](http://www.wowhead.com/npc=21877/karsius-the-ancient-watcher) is spawned to kill him so is totally bugged(I have tried to do some of the temporary ways to do it which were commented in private status or in other bugtrackers reports and nothing worked)

NOTE: This is the alliance and not the horde version(might have put the event to start on horde version but the alliance version do not start)

Wowhead Link: [Teron Gorefiend, I am...](http://www.wowhead.com/quest=10645/teron-gorefiend-i-am)
How it should work: [Teron Gorefiend, I am...](https://www.youtube.com/watch?v=xci_Dzxocp4)

**Comment by karama300** [comment]
confirmed on 17.01.2016

**Comment by Karathe** [comment]
Confirmed as for 21.05.2016

**Comment by Bildo** [comment]
fixed

**Comment by Aival94** [comment]
@Bildo Alliance quest still not working.Want to make me other report for this bug(do not know about Horde one)
