### ISSUE TITLE
[EN][Other][Mount Hyjal][Shrine of Aviana]Phasing problem

### ISSUE THREAD

**Issue by Haz3L** [Atlantiss/BugTracker#5530]
When you stand here you see mobs and everything.

http://i.imgur.com/KSSSg4i.jpg

Two steps forward and everything dissappears.

http://i.imgur.com/QtLKEMX.jpg

**Comment by Anhaeyn** [comment]
And you can't finish quests, we're in some different phase and there's no other npcs like Tortolla etc.

**Comment by Emielos** [comment]
I am having the same exact issue, and it is really annoying.

**Comment by Lebiedz** [comment]
It happens when you complete the "main" part of hyjal quest chain up to quests from Hamuul Runetotem at Sanctuary of Malorne. This is where the phase changes so you can start firelands invasion chain at lvl 85. 
Last quest required for the phase to change: [Aessina's Miracle] (http://www.wowhead.com/quest=25372/aessinas-miracle)

**Comment by Aival94** [comment]
I think this one is now fixed.

**Comment by tomatosz** [comment]
Issue still persists, I can confirm that the phasing issue occurs at Aessina's Miracle.

**Comment by tomatosz** [comment]
Post an indirect fix on the forums:

https://community.atlantiss.eu/index.php?/topic/15074-quest-the-last-living-lorekeeper-hyjal-phasing-issue/

**Comment by Jenovas** [comment]
Fix in rev 5538
