### ISSUE TITLE
[EN][Spell]Windfury ICD

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#5531]
http://www.wowhead.com/spell=33757/windfury

how it should work:
WF should have 3 sec ICD (+- 0.2 according to blizz forum entries ) -> http://us.battle.net/wow/en/forum/topic/2140506118
    Posted by Marashka
    I'd think the best way to check this out would be to run a log or other testing setup that provides time stamps and just let it go for a while (I'd think autoattacking a dummy would be fine, unless specials now have some differing interaction with WF)--if you ever see procs closer together than ~2.8 seconds, something may have changed.

This would be an ideal. And to clarify on Marashka's 2.8 seconds, the Windfury ICD is 3 seconds plus +/-.2 seconds. It isn't always an exact 3 seconds, but we round to simplify when explaining it. :P 

How it works on our server : wf can proc in time lower than 3 sec, my best was 1 sec but didnt capture it on ss. here goes 2 sec icd.
http://imgur.com/SvpBSnE

**Comment by anxanas** [comment]
Nerf enhancement please, and fix warlocks metamorphis, soul link and doomguard, ty =))

**Comment by BialyADI** [comment]
Really, WF on our server dont heave ICD too ;o?
And that: https://github.com/Atlantiss/BugTracker/issues/5439 is major bug too.
Shamans Procs it out of controll some times.

**Comment by anxanas** [comment]
Flametongue was fixed recently, so thats not a problem

**Comment by blinkmaster** [comment]
nope, the flametongue bug still exist :) but its not about this wf so /shoo

**Comment by BialyADI** [comment]
Yes, Flametongue Weapon proc from main and off hand.
But that bug with WF proc is big issue.

I remember that Blizz remove ICD from WF at the end of Miss of Pandaria.
But no on Cata thats why Shamans on our server do that big Dmg and first Dmg from WF procs...

**Comment by Jenovas** [comment]
Windfury cooldown work properly. On your SS the time sould have been 2.8 sec not 2 sec.
Just did tests with a Shaman with 200% haste giving both my main-hand and off-hand a speed of 0.4.
Windfury procs around every 3sec. 

I also did ten 1 minute tests with 200% haste + normal rotation to see how many times I can get Windfury to proc. The max amount of procs that can happen in 1 minute is 20. My max amount of procs was 18. 

Closing.
