### ISSUE TITLE
[EN][Warlock][Talent] - Soul Siphon + Drain Soul

### ISSUE THREAD

**Issue by meowmewo** [Atlantiss/BugTracker#5922]
After noticing something wierd in Drain Soul damage i did few tests. Ok, so i tested Soul Siphon with 2 Affliction specs . 1 with 1/2 and 1 with 2/2 becouse u cant go 0/2.
Link - http://cata-shoot.tauri.hu/?spell=17805
Results : 

With 2/2 it gives 6% additional dmg to Drain soul but thats it. Instead of giving 6% per dot on targets, it just gives it 6% dmg bonus regardless of how many dots. Always only 6% no matter if there are dots or not. It should give 6% per dot, total of 18% with 3 dots on.

With 1/2- same result but with 3%.

So instead of giving 6 / 3% bonus dmg to Drain soul PER Dot on the target. It gives Drain Soul a static 6 / 3% dmg increase, Instead a 3x6% per dot aka total of 18%,

Both This bug + Death's Embrace bug result in 24% less dmg to Drain Soul ticks under 25% of Bosses Health = Major Bug.

**Comment by meowmewo** [comment]
Link to Death's Embrace Bug - https://github.com/Atlantiss/BugTracker/issues/5916

**Comment by kadi2** [comment]
Soul Siphon gives unwanted 6% damage increase to Drain Soul and Drain Life, that stacks multiplicative with above spells regladless of ammount effects we have on the target.

I am not sure how Drain Life should act with warlock's curses. It actually interracts difrently with some effects on the target.

Works:
Curse of Weakness - 702
Unstable Affliction - 30108
Bane of Agony - 980
Corruption - 172
Curse of the Elements - 1490
Curse of Tougness - 1714
Seed of Corruption - 27243


Doesn't work:
Immolate - 348 // I know it's not affliction spell, but in case.
Bane of Doom - 603
Jinx - 86105 // Just tested in case.

**Comment by anxanas** [comment]
@kadi2  can you please rephrase or something i didnt really get your point, does it give 6%*18% or only 6% increase?

**Comment by meowmewo** [comment]
Have no idea what ur saying, im just saying that Instead of getting 6% bonus dmg to Drain soul per dot (up to 3x dots = 18%) we get a statick of 6% regardless of dots.

**Comment by anxanas** [comment]
I just tested this with DR damage addon, sry nedev but it works perfectly =)))

**Comment by kadi2** [comment]
0 Dots on target - we get 1.06 bonus to DL- Should not get 1.06
1 Dot on target - we get 1.06*1.06 bonus to DL- Should get 1.06
2 Dots on target - we still get only 1.12*1.06 to DL- Should get 1.12
3 Dots on target - we still get only 1.18*1.06 to DL- Should get 1.18

**Comment by meowmewo** [comment]
Its not 6%. its 12%

**Comment by anxanas** [comment]
Kadi so it does too much damage or too little?

**Comment by kadi2** [comment]
@anxanas  Drain Life does too much, but Drain Soul deals too low damage...

**Comment by Illusie** [comment]
god bless you more Warlock bug reports plz :)

**Comment by Wolffenstein** [comment]
Fixed in rev 4822.

**Comment by anxanas** [comment]
ty

**Comment by meowmewo** [comment]
Not fixed. It doesnt give bonus for the 3rd dot. Reaches 12% . doesnt give 18.

**Comment by kadi2** [comment]
@meowmewo 
It works for me fine with Drain Life and Drain Soul.

**Comment by meowmewo** [comment]
Test it again. it doesnt give the 6% bonus for the 3rd dot.

**Comment by kadi2** [comment]
Couldn't reproduce it, tried with any combinations.

**Comment by meowmewo** [comment]
Drain Soul man.. put 1 dot. drain soul. put 2 dots. Drain souk. Put 3 dots Drain soul.. the dmg with 2 dots and 3dots is the same...

**Comment by meowmewo** [comment]
Nevermind. It seems it works sometimes, and sometimes it doesnt. I dont know how to report that. Guess we will be playing like this for a while.

**Comment by kadi2** [comment]
Try after server restart.

**Comment by meowmewo** [comment]
I found out whats bugged now. It counts Curse of the Elements as one of ur dots.

**Comment by kadi2** [comment]
I am not sure if it's a bug:
http://wow.allakhazam.com/forum.html?forum=243&mid=117619349913079229

**Comment by meowmewo** [comment]
2007...

**Comment by meowmewo** [comment]
Ok then i guess ur right.

**Comment by kadi2** [comment]
The only thing i consider is that Drain Life, Drain Soul, Fear maybe should be added to the list....

**Comment by meowmewo** [comment]
What list...

**Comment by kadi2** [comment]
Affliction effects list that should interract with Soul Siphon.
http://wow.gamepedia.com/Soul_Siphon
