### ISSUE TITLE
[EN][Molten Front][Item] Zen'Vorka's Cache

### ISSUE THREAD

**Issue by LaveniaGithub** [Atlantiss/BugTracker#5979]
http://www.wowhead.com/item=71631/zenvorkas-cache#comments

The bag was empty when I opened it. Shouldn't be possible.

**Comment by xolon** [comment]
I believe its reported already, either here or on forum

**Comment by Bildo** [comment]
fixed

**Comment by Porobiony** [comment]
Well, i had 3 or 4 bags empty in a row, so i guess it's not fixed

**Comment by Lebiedz** [comment]
I confirm, the same thing happened to me.

**Comment by LaveniaGithub** [comment]
I can confirm as well. Got a few empty caches since then.
