### ISSUE TITLE
[EN][Priest][Spell][Mind Flay+Shadowy Apparition]

### ISSUE THREAD

**Issue by pignon87** [Atlantiss/BugTracker#6301]
**What's Wrong:**
A new bug started from yesterday. Everytime a Shadowy Apparition procs,it interrupts your Mind Flay channeling. This is a major bug and ruin the damage of shadow priests. Pls fix it.
Also Mind Flay was already bugged in another way https://github.com/Atlantiss/BugTracker/issues/4308
**How Should it be**
Shadowy Apparition procs shouldn't intterrupt your channeling/casts

**Comment by BiliBee** [comment]
Confirmed, Shadowy Apparition interrupts Mind Flay. Please fix it, it's major DPS loss.

**Comment by Tetriandoch** [comment]
Confirmed too. Not only affects Mind Flay channeling, but Mind Sear too. I suppose it affects all the channelings

**Comment by Larousene** [comment]
Confirmed

**Comment by nukha** [comment]
Confirmed.

**Comment by shevix** [comment]
Confirmed, Interrupted also my mind blast looks like it breaks all casting.

**Comment by Bastek** [comment]
Fixed in rev. 4881

**Comment by shevix** [comment]
its not fixed, happed to me again today morning with mind flay.

**Comment by pignon87** [comment]
@shevix It's fixed.Probably you tested it when the rev was not applyed yet.
