### ISSUE TITLE
[ENG][Profession][Archaeology][Zul'Drak] Bugged troll dig site

### ISSUE THREAD

**Issue by AnubisMRM** [Atlantiss/BugTracker#7667]
I encountered a bugged archaeology dig site. The item cannot be surveyed since it is probably high in the air or underground. I tried surveying inch by inch, but I can't manage to reveal the fragments. I don't have mods to give you the exact location so I attached the map as well.
Is there any way of resetting the sites (besides relogging because it does not work) since I have another 2 bugged sites (Night Elf in Feralas and an Orc/Draenic site in Shadowmoon Valley, Outland)?
![wowscrnshot_061816_174804](https://cloud.githubusercontent.com/assets/19762678/16171705/8a421a8c-357e-11e6-83f9-ecd9ccbf524a.jpg)
![wowscrnshot_061816_175804](https://cloud.githubusercontent.com/assets/19762678/16171706/8e8aac12-357e-11e6-8a17-46270a9bfba4.jpg)

**Comment by Luna-maria** [comment]
relogging fixed it for me, but I had the same thing happen at that troll digsite in zul'drak

**Comment by AnubisMRM** [comment]
After multiple re-logins the site was reset, going now to check if the other 2 sites are ok.

**Comment by AnubisMRM** [comment]
The issue was fixed for the site in Feralas as well. To be noted that in order to reset the dig site I logged out of the account (reached the log in screen, not just returned to the character selection screen) and relogged again.

**Comment by GralRamon** [comment]
The DigSite in Feralas still broken, I logout and relogged plenty of time, it did not work... I dont know what to do ^^, working on 3 digsites while farming Tol'vir Artifacts is not helpfull.
