### ISSUE TITLE
Twilight Highlands has bug spot!

### ISSUE THREAD

**Issue by Melisara** [Atlantiss/BugTracker#7919]
Everyone who get close to Firebeard's Patrol get instant error #132 !!!

**Comment by LaveniaGithub** [comment]
Should be fixed after last server restart.

**Comment by BAndysc** [comment]
Let me know if client still crashes (after yesterday's update)
