### ISSUE TITLE
[EN][Quest][Eastern Plaguelands] Nobody to Blame But Myself

### ISSUE THREAD

**Issue by muddykinz** [Atlantiss/BugTracker#799]
Nobody to Blame But Myself:

How It Should Work:
http://www.wowhead.com/quest=27489
you take the caravan to the tower and there's an argument between the blood elf and the tag alongs.

How It Works:
The caravan like breaks into two pieces, the first being the part that the horses should be pulling it from, the second the caravan itself.
the first piece starts moving on it's own, forward, and the second piece, trying to catch up to the first flings all the riders off of it and disappears.

And yes, this is a repeating bug, making the quest unplayable.

**Comment by Wolffenstein** [comment]
Fixed in rev 4199.

**Comment by stewazy** [comment]
Hello i have to say it is still broken because the phasing keeps breaking, when i get on the caravan i get autodismounted from it after a few steps i don't know what the problem is :(
