### ISSUE TITLE
[EN][NPC] Big Zokk Torquewrench <Classic Weapons>

### ISSUE THREAD

**Issue by ghost** [Atlantiss/BugTracker#8254]
I wanted to get the [http://www.wowhead.com/item=77574/replica-high-warlords-battle-axe](url) but the vendor that is [http://www.wowhead.com/npc=54649/big-zokk-torquewrench](url) doesn't work whenever i talk to him nothing happens

**Comment by Piklo** [comment]
http://www.wowhead.com/npc=54649/big-zokk-torquewrench#comments:id=1591043
"If you get a "Item is locked" error it is because you do not have the Feat of Strength for Legionnaire/Knight-Captain or higher under the old PvP system."

**Comment by Ylber31** [comment]
Nope i don't get any error or nothing. It just doesn't open the weapon menu! i tried the other vendor "http://www.wowhead.com/npc=54648/leeni-smiley-smalls" for the High Warlord's Gear and it worked i could transmog it and everything. Only the Weapons Vendor doesn't work!

**Comment by krecik88** [comment]
fixed in 5287

**Comment by mgshaper** [comment]
unfortunatelly, it's still not working :/ - this NPC (Big Zokk) hasn't any items in his "offers"

**Comment by Piklo** [comment]
http://www.wowhead.com/npc=54649/big-zokk-torquewrench#comments:id=1587191

This NPC will sell the replica Grand Marshal and High Warlord weapons to any who have the original Feat's of Strength (Grand Marshal or High Warlord) or the new rated battleground ranks of Grand Marshal or High Warlord.
