### ISSUE TITLE
[EN][Priest][Discipline] Penance

### ISSUE THREAD

**Issue by Illusie** [Atlantiss/BugTracker#8708]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

http://cata.openwow.com/spell=47540

**Description**: Sometimes Penance miss 3rd tick.

**Current behaviour**: Using Penance, heal 2 ticks out of 3

**Expected behaviour**: Penance should always make 3 ticks no matter what your Haste is.
The haste only effect how fast the ticks will come

**Steps to reproduce the problem**:

1.  use Penance on someone.
2.  Sometimes it will only 2 ticks
3. 

Screenshot:
http://i.imgur.com/ijIUjjF.jpg

It really hard to catch when it does 2 ticks instead of 3 ticks and also be fast enough to catch it and click screenprint key. ^^ tried my best.
Yes I am 100% sure Im not moving before 3rd tick appear.

**Revision**: rev. 5269

**Comment by Piklo** [comment]
you can see current server revision by typing ".s in" in chat

**Comment by debtheone** [comment]
https://github.com/Atlantiss/BugTracker/issues/4852 they'v fixed it long time ago maybe its bugged again who knows gonna test
btw im curious whats the point of hiding ur nickname and stuff rofl?>

**Comment by Illusie** [comment]
it got fix? i didnt seen any on changelog

**Comment by debtheone** [comment]
bump its rly huge..

**Comment by sigmundfreud2016** [comment]
bump, just started to lvl my priest as disc and its really annoying

**Comment by debtheone** [comment]
bump?

**Comment by Zikatirol** [comment]
bump, still, it sometimes ticks 2 times instead of 3 even as heal

**Comment by purabasura666** [comment]
July 3, 2017: Penance still bugged. Used as damage or healing, it often ticks twice instead of three times. This represents a 33% loss on a cornerstone spell for discipline priests. Many thanks!

**Comment by Goregrin** [comment]
Bump, the bug is still here...

**Comment by TranceAccount** [comment]
Did any of you actually check the combat log?

**Comment by Piklo** [comment]
fixed in [rev5472 ](https://atlantiss.eu/changelog#rev5472)

**Comment by Illusie** [comment]
Still not working as It should be. I did a few tests today.
I'm getting 3x Grace but the last tick is not healing. There no evidance for healing recieve not in combatlog, frames, MSBT.

**Comment by Piklo** [comment]
"Steps to reproduce the problem" please

**Comment by Illusie** [comment]
cast penance like i did 30-50 times in row cancelaura Grace and watch combatlog?

combatlog will say:
X Penance heals Y for ... 
X gains X Grace (1)
X Penance heals Y for ...
X gains X Grace (2)
X gains X Grace (3)


what you expect to see on combatlog is

X Penance heals Y for ... 
X gains X Grace (1)
X Penance heals Y for ...
X gains X Grace (2)
X Penance heals Y for ...
X gains X Grace (3)

I also looking at Frames and MSBT addon (scroll text) It miss the last tick there aswell.

**Comment by lamaATS** [comment]
Penance was casted on self or player/npc/pet? (X and Y suggest different target than caster)

**Comment by TranceAccount** [comment]
Try naked?
