### ISSUE TITLE
[EN][Spell][Shaman] Lava Lash improperly consuming Unleash Flame

### ISSUE THREAD

**Issue by Tetuz** [Atlantiss/BugTracker#9008]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Hello, I noticed a bug with the interaction between Lava Lash and the buff given by Unleash Elements, Unleash Flame. I tested it with 50 hit of Lava Lash each time, removing any proc (landslide, trinket) and with the same weapon (http://cata.openwow.com/item=67471) and without Serring Totem to avoid any stat or damage changes. It appears that Unleash Flames doesn't increase lava lash damage (and it shouldn't do it) but gets consumed in the meantime (but it does), so basically if you cast Lava Lash between Unleash Elements and flame shock it will be a dps loss because flame shock won't benefit of the 20% damage increase.
Lava Lash damage without the Unleash Flames buff
![wowscrnshot_031217_125229](https://cloud.githubusercontent.com/assets/26360436/23832001/c4fceba4-072c-11e7-8b4d-7c43e7cbe053.jpg)

Lava Lash damage while consuming the Unleash Flames buff
![wowscrnshot_031217_130736](https://cloud.githubusercontent.com/assets/26360436/23831980/3271207a-072c-11e7-8204-c2ef4f909fe7.jpg)

As you can see the damage is pretty much the same, if the Unleash Flame increased it, it will be 20% more, so the max damage should be around 18k.

**Current behaviour**: When you have Flame Shock on the target and you cast Unleash elements and then Lava Lash, the Unleash Flame buff gets consumed, apparently without modifying any damage. If you don't have Flame Shock on the target this doesn't happen.

**Expected behaviour**: According to Wowhead (http://www.wowhead.com/forums&topic=176349/the-shaman-cataclysm-faq-dump-your-question-here-updated-regularly in the enhancement section) Lava Lash shouldn't interact with Unleash Flames so the buff should only get consumed by Lava Burst or Flame Shock.

**Steps to reproduce the problem**:

1. Cast Flame Shock on target
2. Cast Unleash elements while having a Flametongue imbue
3. Cast Lava Lash and che the Unleash Flame buff

**Revision**: 5340

**Comment by xShojirox** [comment]
In the title you should change [Class] to Shaman, and I would probably also change the title wording to something like Lava Lash Improperly Consuming Unleash Flame buff, but that is more just personal preference. 

As for the actual issue itself, I tested it. As you said, while Flame Shock was on the target, Lava Lash consumed the Unleashed Flame buff but didn't seem to provide any improved damage in Lava Lash.

So while it does seem to be proper that it is not providing any damage increase to Lava Lash (as from what I have also looked up online), it is wrong that it consumes the Unleashed Flame buff while the Flame Shock debuff is on the target.

**Comment by gogenks** [comment]
bump

**Comment by Tetuz** [comment]
Done some more tests on mobs around Sethria's roost in mount hyjal (just for the high hp). On them it works correctly, but on target's dummy it's bugged. If someone can test this on raid bosses please let us know if it works.

**Comment by Tetuz** [comment]
Seems the problem is only affecting 3 of stormwind's target dummies, the 2 heroics with the expert target dummy in the middle (the ones i got in picture). So I think it's safe to say that it works.

**Comment by ashrasmun** [comment]
This is not fixed. Sorry for misleading comment on my part. Evidence and explanation in Polish is below. Recorded today, on rev 5769

https://www.youtube.com/watch?v=qGhJKy200f8

Please reopen this issue.
