### ISSUE TITLE
[PL] [Instance-Classic] Blackrock Depths

### ISSUE THREAD

**Issue by kukukz** [Atlantiss/BugTracker#946]
Po zwolnieniu zębatki przejscie sie nie otwiera.

**Comment by Oldworldgame** [comment]
Proszę o naprawienie tego przejścia asap ponieważ potrzebuje receptury na http://www.wowhead.com/item=18232 która powinna leżeć koło bosa http://www.wowhead.com/npc=8983 
Z góry dziękuje ;)

**Comment by Tj20** [comment]
Not sure if this is the bug mentioned above or if I should open a new issue... I try it here:

**Expected Behaviour:** If you're in Dungeon Finder queue for *BRD - Detention Block* or *BRD - Upper City*, the Dungeon Finder should place you at the main entrance. Groups for Upper City may use one of the Abandoned Mole Machine near the entrance to teleport to the "Grim Guzzler" to shorten the length of time clearing the dungeon. [Source](http://wow.gamepedia.com/Blackrock_Depths#Dungeon_Finder_Tips)

**Observed Behaviour:** The Dungeon Finder spawns you at the back entrance of BRD, near the portal to Molten Core. The door to the earlier part of the dungeon is locked, so you can essentially only do two bosses: Magmus and Emperator Thaurissian. 

If you were in queue for the Detention Block, you won't get your satchel of exotic goods because you can't reach your target High Interrogator Gerstahn. 

![map](http://i.imgur.com/rDOqJ8E.jpg)

**Comment by Wolffenstein** [comment]
Dungeon Finder spawn position and Abandoned Mole Machines fixed in rev 4226.

**Comment by Jetrean15** [comment]
Hope the locking mechanism for the bridge get's fixed soon. A lot of important plans and schematics beyond that point.  Haven't had the incentive to log in any since this is still an issue,

**Comment by Wolffenstein** [comment]
Fixed in rev 4287.

**Comment by Jetrean15** [comment]
Why is this closed? This isn't fixed. The Shadowforge Lock is still broken and you still can't go across the bridge to where the Goleamancer and Gnome technicians are. That's also the only way to gain entry into the Grim Guzzler. Lol got my hopes up for nothing.

**Comment by Tj20** [comment]
Rev.  4287 ist still "waiting for update" according to the changelog. So the fix is not live yet.
