### ISSUE TITLE
[EN][Raid][Dragon Soul][Ultraxion][Death Knight][Dancing Rune Weapon]

### ISSUE THREAD

**Issue by Katonetwo** [Atlantiss/BugTracker#9919]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Dancing Rune Weapon isn't working on Ultraxion as it should

**Current behaviour**: Dancing Rune Weapon gives a parry buff when activated, but does not summon the actual Rune Weapon pet to attack Ultraxion.

**Expected behaviour**: Dancing Rune Weapon should summon a Rune Weapon to attack Ultraxion.

**Steps to reproduce the problem**:

1. Be a Blood Death Knight at Ultraxion
2. Use Dancing Rune Weapon
3. Notice how your DPS gets lower rather than higher due to your pet not attacking/existing

**Revision**: 5693

**Comment by stanq87** [comment]
#9906 also pet

**Comment by TranceAccount** [comment]
Maybe it spawns on the wrong spot?

**Comment by firemagegodx** [comment]
May add that this happens to Shadowfiend aswell. Would toss the guess that they spawn behind the boss and fall to the ground, since they hit a few times before they stop (4-5 times maybe).

**Comment by pelekon** [comment]
should be fixed in  5732 but I will leave it open until I get proper feedback

**Comment by Katonetwo** [comment]
note that it still doesn't work (except for those 7 hours that one time)

please reopen :p
