### ISSUE TITLE
[EN][Professions][Mining][Northrend] Underlying issues around mining nodes in general in northrend

### ISSUE THREAD

**Issue by Ghobashy97** [Atlantiss/BugTracker#9974]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: So, i went around zul'drak and scouted most mining nodes in the area, and marked on a map in paint the location of all the hidden nodes i found.. so here's the map with the blue dots on the map being the location of HIDDEN nodes. Keep in mind, that some nodes are also near other nodes, so you have to mine all uncovered nodes near that exact spot, then you will find the hidden one 
Imgur: https://imgur.com/a/Z7mcC

Also the spawn rates of different types of ore seems to be quite off, Saronite ores should be spawning alot more frequently in zones like icecrown, storm peaks and sholazar basin, also after ~6 hours of mining in most  of northrend, i managed to accumulate LESS than 1 stack of titanium ore, and less than 12 stacks of saronite ores... and there was absolutely nobody farming them, even if i were to mine the broken nodes in icecrown, i would have had ~30-35 stacks at the most.. whereas on retail right now, or on wrath in general i would have alot more ores than that... especially titanium
here are some database/wiki links to those:
https://wotlk-twinhead.twinstar.cz/?object=189981
http://wowwiki.wikia.com/wiki/Saronite_Ore
http://www.wowhead.com/object=189980/saronite-deposit
https://wotlk-twinhead.twinstar.cz/?object=191133
http://wowwiki.wikia.com/wiki/Titanium_Vein
http://www.wowhead.com/object=191133/titanium-vein

**Current behaviour**: Nodes are not accessible, i.e. they are hidden underneath textures
also spawn frequency for different types of are are not how they should be, saronite and titanium should be spawning ALOT more frequently than they are right now
**Expected behaviour**: they should be above the ground

**Steps to reproduce the problem**:

1. learn mining
2. turn on find minerals
3. fly around in northrend

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)
https://imgur.com/a/bLgCO

**Comment by TranceAccount** [comment]
Titanium spawns from Saronite deposits.

**Comment by tomatosz** [comment]
Thanks for your effort, I'm working my way through the saronite nodes.

**Comment by tomatosz** [comment]
> Nodes are not accessible, i.e. they are hidden underneath textures

Fixed in rev. 5723

**Comment by Ghobashy97** [comment]
The issue is not fixed, i went mining in zul'drak and almost all the same nodes were hidden again

**Comment by TranceAccount** [comment]
The fix is still waiting for a server update.
